item {
    name: "0",
    id: 1,
    display_name: "Alpukat"
}
item {
    name: "1",
    id: 2,
    display_name: "Buah Naga"
}
item {
    name: "2",
    id: 4,
    display_name: "Jambu Biji"
}
item {
    name: "3",
    id: 5,
    display_name: "Kedondong"
}
item {
    name: "4",
    id: 6,
    display_name: "Kesemek"
}
item {
    name: "5",
    id: 7,
    display_name: "Kiwi"
}
item {
    name: "6",
    id: 8,
    display_name: "Lemon"
}
item {
    name: "7",
    id: 9,
    display_name: "Manggis"
}
item {
    name: "8",
    id: 10,
    display_name: "Markisa"
}
item {
    name: "9",
    id: 11,
    display_name: "Salak"
}
item {
    name: "10",
    id: 3,
    display_name: "Sawo"
}
